### ISSUE TITLE
Issue arrises when words in the class list are not in the dataset

### ISSUE THREAD

**Issue by JohnGiorgi** [yumeng5/WeSTClass#1]
First off, thanks for open sourcing the code!

I am trying to topic model with my own dataset. I set it up to look like the `yelp` dataset and modify the code accordingly. However, an error

```
Traceback (most recent call last):
  File "main.py", line 200, in <module>
    word_sup_array = np.array([np.array([vocabulary[word] for word in word_class_list]) for word_class_list in word_sup_list])
  File "main.py", line 200, in <listcomp>
    word_sup_array = np.array([np.array([vocabulary[word] for word in word_class_list]) for word_class_list in word_sup_list])
  File "main.py", line 200, in <listcomp>
    word_sup_array = np.array([np.array([vocabulary[word] for word in word_class_list]) for word_class_list in word_sup_list])
KeyError: 'algebra_and_number_theory'
```

is thrown on the following line:

https://github.com/yumeng5/WeSTClass/blob/70d8780a17c36afde63d477d44538833ffffe87b/main.py#L194

It looks like this is because one of my provided class names (`algebra_and_number_theory`) in `${dataset}/classes.txt` is not contained within the vocabulary. 

I am confused as to wether this is my fault or a bug in the code? I wouldn't expect class names to be in the vocabulary, so I am leaning toward the latter. In either case, any help would be much appreciated!

**Comment by yumeng5** [comment]
Hi John,

The error is expected if the provided class label surface name is not in the vocabulary, in which case the class name will not appear in the word embedding trained on the corpus, and there is no way to represent the class name as a word vector for all subsequent tasks. 

Here are some possible solutions for this:
1. Change the type of weak supervision. The algorithm also supports the use of class-related keywords as supervision. For example, if the class name is ``algebra_and_number_theory``, you may come up with some related word tokens as supervision, such as ``algebra``, ``arithmetic`` and ``number``. The ideal choice of keywords would be those that can distinguish the target class from all other classes.
2. Use some phrase mining tool to detect phrases and pre-process the corpus. The current algorithm trains word embedding for each single word token. Specifically, if a phrase ``algebra and number theory`` appears in the corpus, it will not be treated as a phrase, and each word's embedding will be trained independently. You can try to connect these words with underscore characters so that the algorithm treats phrases as a whole. If the number of classes is small, you can even try to manually construct phrases for class names only.
3. Use pre-trained embedding instead of training the embedding on your current corpus. Some available pre-trained embedding might contain phrases and/or out vocabulary words. You will need to modify the function ``train_word2vec`` in ``main.py`` to load pre-trained embedding. You might also need to manually add the class names into the variable ``vocabulary`` in ``main.py``.

I am not sure which of the solutions work best in your case, but I would suggest trying 1 and 2 first, because pre-trained word embedding (3) may not suit your corpus well.

**Comment by JohnGiorgi** [comment]
Thanks for the detailed response!

My class labels are almost all multiple tokens long. So I think that I will split them into individual tokens, drop any stop words, and then simply use these lists of tokens as keywords (my `sup_source`).

Hopefully that works. Thanks again!
