### ISSUE TITLE
Use spherical text embeddings?

### ISSUE THREAD

**Issue by theashworld** [yumeng5/WeSTClass#3]
Has anyone tried using https://github.com/yumeng5/Spherical-Text-Embedding instead of w2v in the code?

**Comment by yumeng5** [comment]
Hi,

Thanks for the question. Personally I haven't tried to replace word2vec with my spherical embedding in this WeSTClass framework. It is completely reasonable to do so, but I wouldn't expect the results to be significantly different since both algorithms are still unsupervised embeddings and they are not designed to distinguish the categories during embedding learning. 

To learn discriminative embeddings from weak supervision (label names or keywords), I would suggest taking a look at another embedding framework [CatE](https://github.com/yumeng5/CatE). I did try to replace word2vec with CatE in WeSTClass and observed better classification results (described in the [CatE paper](https://arxiv.org/pdf/1908.07162.pdf)).

Let me know if you have any other questions!

Best,
Yu
